version: '2'

services:

    #######################
    # Amalgam8 controlplane
    #
    registry:
        image: amalgam8/a8-registry
        ports:
            - "8001:8080"
        environment:
            - A8_STORE=redis
            - A8_STORE_ADDRESS=redis:6379
        links:
            - redis

    controller:
        image: amalgam8/a8-controller
        ports:
            - "8002:8080"
        environment:
            - A8_DATABASE_TYPE=redis
            - A8_DATABASE_HOST=redis://redis:6379
        links:
            - redis

    redis:
        image: redis:alpine
    
    ######################
    # A8 room services
    #
    mediator:
        image: gameon-a8-room/mediator:latest
        ports:
            - "3000:3000"
        links:
            - registry
            - controller
                
    room:
        image: gameon-a8-room/room:latest
        links:
            - registry
            - controller
        environment:
            - VERSION=v1
            - A8_SERVICE=room:v1
